package com.ikolvi.tracelet.example

import android.util.Base64
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        
        // Register a safe, non-conflicting debug channel for the parity check
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "com.tracelet/debug")
            .setMethodCallHandler { call, result ->
                if (call.method == "debugVerifyRustParity") {
                    try {
                        // Dynamically load the classes generated by UniFFI
                        val geoClass = Class.forName("uniffi.tracelet_core.GeoConfig")
                        val motionClass = Class.forName("uniffi.tracelet_core.MotionConfig")
                        
                        // Extract all compiled fields inside the JVM class definitions
                        val geoFields = geoClass.declaredFields.map { it.name }
                        val motionFields = motionClass.declaredFields.map { it.name }
                        
                        // Expected properties defined in Dart Config models
                        val expectedGeo = listOf(
                            "stopAfterElapsedMinutes", "maxMonitoredGeofences", "periodicLocationInterval",
                            "periodicDesiredAccuracy", "sparseMaxIdleSeconds", "batteryBudgetPerHour",
                            "enableDeadReckoning", "deadReckoningActivationDelay", "deadReckoningMaxDuration",
                            "resolveAddress"
                        )
                        val expectedMotion = listOf(
                            "isMoving", "activityRecognitionInterval", "minimumActivityRecognitionConfidence",
                            "stopDetectionDelay", "stopOnStationary", "stationaryRadius", "useSignificantChangesOnly",
                            "stillThreshold", "stillSampleCount", "motionDetectionMode", "speedMovingThreshold",
                            "speedStationaryDelay", "stationaryTrackingMode", "stationaryPeriodicInterval",
                            "stationaryPeriodicAccuracy", "speedWakeConfirmCount"
                        )
                        
                        // Detect which of these are physically missing in the Rust-compiled UniFFI class
                        val missingGeo = expectedGeo.filter { !geoFields.contains(it) }
                        val missingMotion = expectedMotion.filter { !motionFields.contains(it) }
                        
                        result.success(mapOf(
                            "missingGeo" to missingGeo,
                            "missingMotion" to missingMotion
                        ))
                    } catch (e: ClassNotFoundException) {
                        result.error(
                            "CLASS_NOT_FOUND", 
                            "Tracelet UniFFI classes not found. Is the plugin installed and compiled?", 
                            e.message
                        )
                    } catch (e: Exception) {
                        result.error("REFLECTION_ERROR", e.message, null)
                    }
                } else if (call.method == "debugCrashModelLoad") {
                    // #183 Phase 2b: verify the loader (download → SHA-256 verify →
                    // AES-GCM decrypt → cache) end-to-end on-device. Runs off the
                    // main thread because the loader does network I/O.
                    val url = call.argument<String>("url")!!
                    val sha = call.argument<String?>("sha256")
                    val keyB64 = call.argument<String>("key")!!
                    // Optional feature vector to score (defaults to the synthetic
                    // blob's single feature). For the real model pass the 5 features
                    // in featureNames order: peak_g, dv, gyro_peak_dps, speed_max, mean_g.
                    val features = call.argument<List<Double>>("features") ?: listOf(3.0)
                    Thread {
                        try {
                            com.ikolvi.tracelet.sdk.crash.CrashModelLoader.decryptionKey =
                                Base64.decode(keyB64, Base64.DEFAULT)
                            // Force a fresh download for the test (ignore any cache).
                            java.io.File(
                                applicationContext.filesDir,
                                "tracelet_crash_model.enc",
                            ).delete()
                            val logs = StringBuilder()
                            val model = com.ikolvi.tracelet.sdk.crash.CrashModelLoader.load(
                                applicationContext, url, sha,
                            ) { logs.append(it).append("; ") }
                            runOnUiThread {
                                if (model == null) {
                                    result.error("LOAD_NULL", logs.toString(), null)
                                } else {
                                    result.success(
                                        mapOf(
                                            "treeCount" to model.treeCount().toInt(),
                                            "featureNames" to model.featureNames(),
                                            "proba" to model.predictProba(features),
                                        ),
                                    )
                                }
                            }
                        } catch (e: Exception) {
                            runOnUiThread { result.error("CRASH_LOAD_ERROR", e.message, null) }
                        }
                    }.start()
                } else if (call.method == "debugCrashModelPredict") {
                    // #183: verify the on-device crash-ML chain end-to-end —
                    // AES-256-GCM decrypt of an encrypted forest blob + tree-walk
                    // inference — using the real rebuilt Rust core.
                    try {
                        val blobB64 = call.argument<String>("blob")!!
                        val keyB64 = call.argument<String>("key")!!
                        val features = call.argument<List<Double>>("features")!!
                        val blob = Base64.decode(blobB64, Base64.DEFAULT)
                        val key = Base64.decode(keyB64, Base64.DEFAULT)
                        val model = uniffi.tracelet_core.CrashModel.fromEncrypted(blob, key)
                        result.success(
                            mapOf(
                                "proba" to model.predictProba(features),
                                "treeCount" to model.treeCount().toInt(),
                            ),
                        )
                    } catch (e: Exception) {
                        result.error("CRASH_MODEL_ERROR", e.message, null)
                    }
                } else if (call.method == "debugImpactGate") {
                    // #183 Phase 3: verify ML gating (Replace mode) through the real
                    // Rust ImpactDetector on-device. Feeds one window with a supplied
                    // crashProba; crashProba < 0 ⇒ rule engine. Returns whether a
                    // candidate fired + its kind/confidence.
                    try {
                        val peakG = call.argument<Double>("peakG")!!
                        val speedMps = call.argument<Double>("speedMps")!!
                        val crashProba = call.argument<Double>("crashProba") ?: -1.0
                        val threshold = call.argument<Double>("threshold") ?: 0.5
                        val detector = uniffi.tracelet_core.ImpactDetector(
                            uniffi.tracelet_core.ImpactConfig(
                                enableCrash = true,
                                enableFall = false,
                                crashGThreshold = 2.0,
                                crashMinSpeedKmh = 25.0,
                                fallGThreshold = 2.5,
                                confirmWindowMs = 15000L,
                                minConfidence = 0.6,
                            ),
                        )
                        val ev = detector.onImpactWindow(
                            peakG, speedMps, 0.0, false, false, false, 0.0, 0.0,
                            System.currentTimeMillis(), crashProba, threshold,
                        )
                        result.success(
                            mapOf(
                                "fired" to (ev != null),
                                "kind" to ev?.kind,
                                "confidence" to ev?.confidence,
                            ),
                        )
                    } catch (e: Exception) {
                        result.error("IMPACT_GATE_ERROR", e.message, null)
                    }
                } else if (call.method == "debugForegroundPromotionGuard") {
                    // #253: a failed foreground promotion must NOT leave the
                    // service marked as a running foreground service.
                    // startForegroundWithNotification() catches the exception,
                    // tears the service down (stopSelf + isRunning=false), and
                    // now RETURNS whether the promotion succeeded, so every
                    // caller assigns `isForegroundService = <result>` instead of
                    // the old unconditional `= true`. The buggy build compiled
                    // the method as Unit (JVM void); the fixed build compiles it
                    // as Boolean. We verify the shipped byte-code directly.
                    try {
                        val svcClass = Class.forName(
                            "com.ikolvi.tracelet.sdk.service.LocationService",
                        )
                        val method = svcClass.getDeclaredMethod(
                            "startForegroundWithNotification",
                        )
                        val returnsBoolean =
                            method.returnType == java.lang.Boolean.TYPE
                        result.success(
                            mapOf(
                                "returnType" to method.returnType.name,
                                "gated" to returnsBoolean,
                            ),
                        )
                    } catch (e: ClassNotFoundException) {
                        result.error(
                            "CLASS_NOT_FOUND",
                            "LocationService not found. Is the plugin installed?",
                            e.message,
                        )
                    } catch (e: Exception) {
                        result.error("FG_GUARD_ERROR", e.message, null)
                    }
                } else if (call.method == "debugIssue286SyncSinkAccumulation") {
                    // #286 VERIFICATION ONLY (no fix): does every attaching
                    // FlutterEngine create a NEW TraceletSyncSink that is never
                    // torn down on detach?
                    //
                    // Reproduces the reporter's environment (workmanager_android
                    // does `FlutterEngine(applicationContext)` per task, then
                    // `engine.destroy()`) and then measures:
                    //   1. how many DISTINCT sink instances the SDK saw
                    //      (1 = process-wide sink, N+1 = one per engine),
                    //   2. whether each abandoned sink's CoroutineScope is still
                    //      active AFTER its engine was destroyed (no teardown),
                    //   3. how many sinks are registered as LocationDataSinks on
                    //      the live LocationEngine (fan-out per persisted fix),
                    //   4. whether the plugin holds the sink in an instance field
                    //      (per engine) or a static/companion holder (shared).
                    try {
                        val requested = call.argument<Int>("engines") ?: 2
                        val engineCount = requested.coerceIn(1, 4)

                        val sdk = com.ikolvi.tracelet.sdk.TraceletSdk
                            .getInstance(applicationContext)

                        // identityHashCode -> strong ref, insertion-ordered, so a
                        // re-registered same instance is not double counted.
                        val observed = LinkedHashMap<Int, Any>()
                        sdk.syncProvider?.let {
                            observed[System.identityHashCode(it)] = it
                        }
                        val baselineSinks = observed.size
                        val registeredBefore = countSyncSinks(readLocationEngine(sdk))

                        val spawned = mutableListOf<FlutterEngine>()
                        repeat(engineCount) {
                            // Plugins auto-register in the constructor, so this
                            // alone runs TraceletSyncPlugin.onAttachedToEngine.
                            val secondary = FlutterEngine(applicationContext)
                            spawned.add(secondary)
                            sdk.syncProvider?.let { p ->
                                observed[System.identityHashCode(p)] = p
                            }
                        }
                        val providerAfterAttach =
                            sdk.syncProvider?.let { System.identityHashCode(it) } ?: 0

                        // Background task finished → engine goes away.
                        spawned.forEach { it.destroy() }

                        val providerAfterDestroy =
                            sdk.syncProvider?.let { System.identityHashCode(it) } ?: 0

                        // Are the sinks belonging to destroyed engines still alive?
                        var aliveAfterDestroy = 0
                        var scopesInspected = 0
                        val scopeStates = mutableListOf<String>()
                        for (sink in observed.values) {
                            val scope = readPrivateField(sink, "scope") ?: continue
                            scopesInspected++
                            val active = coroutineScopeIsActive(scope)
                            if (active == true) aliveAfterDestroy++
                            scopeStates.add(
                                "${sink.javaClass.simpleName}@" +
                                    "${System.identityHashCode(sink)}: " +
                                    when (active) {
                                        true -> "scope ACTIVE"
                                        false -> "scope cancelled"
                                        null -> "scope state unknown"
                                    },
                            )
                        }

                        val pluginClass =
                            Class.forName("com.ikolvi.tracelet_sync.TraceletSyncPlugin")
                        val instanceSinkField = pluginClass.declaredFields.any {
                            !java.lang.reflect.Modifier.isStatic(it.modifiers) &&
                                it.type.name.contains("TraceletSyncSink")
                        }
                        val staticSinkHolder = pluginClass.declaredFields.any {
                            java.lang.reflect.Modifier.isStatic(it.modifiers) &&
                                it.type.name.contains("TraceletSyncSink")
                        }

                        // Android's LocationEngine can drop a sink again, which
                        // is why registerSyncProvider() is able to trim the
                        // foreground list. iOS has no such method.
                        val canUnregister = try {
                            Class.forName(
                                "com.ikolvi.tracelet.sdk.location.LocationEngine",
                            ).declaredMethods.any { it.name == "unregisterSink" }
                        } catch (e: Throwable) {
                            false
                        }

                        result.success(
                            mapOf(
                                "platform" to "android",
                                "canUnregister" to canUnregister,
                                "enginesSpawned" to engineCount,
                                "baselineSinks" to baselineSinks,
                                "distinctSinks" to observed.size,
                                "aliveAfterDestroy" to aliveAfterDestroy,
                                "scopesInspected" to scopesInspected,
                                "scopeStates" to scopeStates,
                                "registeredBefore" to registeredBefore,
                                "registeredAfter" to
                                    countSyncSinks(readLocationEngine(sdk)),
                                "registeredBootAfter" to
                                    countSyncSinks(readBootLocationEngine()),
                                "providerReplacedByDeadEngine" to
                                    (providerAfterDestroy != 0 &&
                                        providerAfterDestroy == providerAfterAttach &&
                                        observed.size > baselineSinks),
                                "instanceSinkField" to instanceSinkField,
                                "staticSinkHolder" to staticSinkHolder,
                            ),
                        )
                    } catch (e: Throwable) {
                        result.error("ISSUE_286_ERROR", e.toString(), null)
                    }
                } else {
                    result.notImplemented()
                }
            }
    }

    // ==== #286 verification helpers (reflection: internals are not public) ====

    private fun readPrivateField(target: Any, name: String): Any? = try {
        target.javaClass.getDeclaredField(name).apply { isAccessible = true }.get(target)
    } catch (e: Throwable) {
        null
    }

    /**
     * The SDK's foreground engine, read through its backing field so an
     * uninitialized `lateinit` returns null instead of throwing.
     */
    private fun readLocationEngine(sdk: Any): Any? = readPrivateField(sdk, "locationEngine")

    /** `LocationService.bootLocationEngine` (companion → static backing field). */
    private fun readBootLocationEngine(): Any? = try {
        val cls = Class.forName("com.ikolvi.tracelet.sdk.service.LocationService")
        cls.getDeclaredField("bootLocationEngine").apply { isAccessible = true }.get(null)
    } catch (e: Throwable) {
        null
    }

    /** Number of TraceletSyncSink instances in a LocationEngine's sink list. */
    @Suppress("UNCHECKED_CAST")
    private fun countSyncSinks(engine: Any?): Int {
        if (engine == null) return -1
        return try {
            val sinks = engine.javaClass.getDeclaredField("sinks")
                .apply { isAccessible = true }.get(engine) as? List<Any?> ?: return -1
            sinks.count { it != null && it.javaClass.name.contains("TraceletSyncSink") }
        } catch (e: Throwable) {
            -1
        }
    }

    /** `scope.coroutineContext[Job]?.isActive`, or null when not determinable. */
    private fun coroutineScopeIsActive(scope: Any): Boolean? = try {
        val ctx = scope.javaClass.getMethod("getCoroutineContext").invoke(scope)
        val jobIface = Class.forName("kotlinx.coroutines.Job")
        val jobKey = jobIface.getField("Key").get(null)
        val keyIface = Class.forName("kotlin.coroutines.CoroutineContext\$Key")
        val ctxIface = Class.forName("kotlin.coroutines.CoroutineContext")
        val job = ctxIface.getMethod("get", keyIface).invoke(ctx, jobKey)
        if (job == null) null else jobIface.getMethod("isActive").invoke(job) as? Boolean
    } catch (e: Throwable) {
        null
    }
}
