import 'package:tracelet_platform_interface/tracelet_platform_interface.dart';

/// A fully-populated [TlConfig] for transport-level tests, with the geofence
/// fields under test in #305 exposed as overrides.
///
/// Extracted so a transport test can vary exactly the keys it cares about
/// without restating every unrelated config block.
TlConfig createMockTlConfig({
  bool geofenceHighAccuracy = false,
  bool androidHighAccuracy = false,
  bool initialTrigger = true,
  int exitAccuracyMax = -1,
}) {
  return TlConfig(
    geo: TlGeoConfig(
      desiredAccuracy: TlDesiredAccuracy.high,
      distanceFilter: 10,
      stationaryRadius: 25,
      locationTimeout: 60,
      disableElasticity: false,
      elasticityMultiplier: 1,
      stopAfterElapsedMinutes: -1,
      maxMonitoredGeofences: -1,
      enableTimestampMeta: false,
      enableAdaptiveMode: false,
      periodicLocationInterval: 900,
      periodicDesiredAccuracy: TlDesiredAccuracy.medium,
      enableSparseUpdates: false,
      sparseDistanceThreshold: 50,
      sparseMaxIdleSeconds: 300,
      enableDeadReckoning: false,
      deadReckoningActivationDelay: 10,
      deadReckoningMaxDuration: 120,
      batteryBudgetPerHour: 0,
      resolveAddress: false,
      filter: TlLocationFilter(
        trackingAccuracyThreshold: 100,
        maxImpliedSpeed: 50,
        odometerAccuracyThreshold: 100,
        policy: TlLocationFilterPolicy.adjust,
        rejectMockLocations: false,
        mockDetectionLevel: 0,
        useKalmanFilter: false,
      ),
    ),
    app: TlAppConfig(
      stopOnTerminate: true,
      startOnBoot: false,
      heartbeatInterval: 60,
      schedule: [],
      remoteConfigTimeout: 30,
      remoteConfigRefreshInterval: 3600,
    ),
    classifier: TlClassifierConfig(
      enableFusedClassifier: false,
      fusedClassifierAuthoritative: false,
      modeSwitchDwellMs: 1000,
      minModeConfidence: 50,
      autoTuneFromTransportMode: false,
    ),
    impact: TlImpactConfig(
      enableCrashDetection: false,
      enableFallDetection: false,
      crashGThreshold: 4,
      crashMinSpeedKmh: 20,
      fallGThreshold: 3,
      confirmWindowMs: 5000,
      minImpactConfidence: 50,
      crashModelThreshold: 0.5,
    ),
    telematics: TlTelematicsConfig(
      enableDrivingEvents: false,
      harshBrakingG: 0.5,
      harshAccelerationG: 0.5,
      harshCorneringG: 0.5,
      speedLimitKmh: 120,
      speedingToleranceKmh: 10,
      speedingMinDurationMs: 5000,
      minSpeedForEventsKmh: 20,
      eventDebounceMs: 1000,
    ),
    android: TlAndroidConfig(
      locationUpdateInterval: 1000,
      fastestLocationUpdateInterval: 500,
      deferTime: 0,
      allowIdenticalLocations: false,
      geofenceModeHighAccuracy: androidHighAccuracy,
      periodicUseForegroundService: false,
      periodicUseExactAlarms: false,
      scheduleUseAlarmManager: false,
      releaseWakelockWhenStationary: false,
      foregroundService: TlForegroundServiceConfig(
        enabled: true,
        channelId: 'tracelet',
        channelName: 'Tracelet',
        notificationTitle: 'Tracking',
        notificationText: 'Tracking active',
        notificationPriority: TlNotificationPriority.defaultPriority,
        notificationOngoing: true,
        showNotificationOnPauseOnly: false,
        actions: [],
      ),
    ),
    ios: TlIosConfig(
      activityType: TlIosActivityType.other,
      useSignificantChangesOnly: false,
      showsBackgroundLocationIndicator: false,
      pausesLocationUpdatesAutomatically: false,
      locationAuthorizationRequest: TlAuthorizationRequest.always,
      disableLocationAuthorizationAlert: false,
      preventSuspend: false,
      useBackgroundActivitySession: false,
    ),
    http: TlHttpConfig(
      syncTelematics: false,
      autoSync: true,
      batchSync: false,
      maxBatchSize: 250,
      method: TlHttpMethod.post,
      autoSyncThreshold: 0,
      syncInterval: 0,
      httpTimeout: 60000,
      locationsOrderDirection: TlLocationOrderDirection.ascending,
      disableAutoSyncOnCellular: false,
      maxRetries: 3,
      retryBackoffBase: 1,
      retryBackoffCap: 60,
      enableDeltaCompression: false,
      deltaCoordinatePrecision: 5,
    ),
    logger: TlLoggerConfig(
      logLevel: TlLogLevel.info,
      logMaxDays: 3,
      debug: false,
    ),
    motion: TlMotionConfig(
      stopTimeout: 5,
      motionTriggerDelay: 0,
      disableMotionActivityUpdates: false,
      isMoving: false,
      activityRecognitionInterval: 1000,
      minimumActivityRecognitionConfidence: 75,
      disableStopDetection: false,
      stopDetectionDelay: 0,
      stopOnStationary: false,
      stationaryRadius: 25,
      useSignificantChangesOnly: false,
      shakeThreshold: 2.5,
      stillThreshold: 0.4,
      stillSampleCount: 25,
      motionDetectionMode: TlMotionDetectionMode.accelerometer,
      speedMovingThreshold: 1.5,
      speedStationaryDelay: 180,
      stationaryTrackingMode: TlStationaryTrackingMode.periodic,
      stationaryPeriodicInterval: 120,
      stationaryPeriodicAccuracy: TlDesiredAccuracy.high,
      speedWakeConfirmCount: 1,
    ),
    geofence: TlGeofenceConfig(
      geofenceInitialTriggerEntry: true,
      geofenceProximityRadius: 1000,
      geofenceInitialTrigger: initialTrigger,
      geofenceModeHighAccuracy: geofenceHighAccuracy,
      geofenceExitAccuracyMax: exitAccuracyMax,
    ),
    persistence: TlPersistenceConfig(
      persistMode: TlPersistMode.all,
      maxDaysToPersist: 1,
      maxRecordsToPersist: -1,
      disableProviderChangeRecord: false,
    ),
    audit: TlAuditConfig(enabled: false, hashAlgorithm: TlHashAlgorithm.sha256),
    privacyZone: TlPrivacyZoneConfig(enabled: false),
    security: TlSecurityConfig(encryptDatabase: false),
    attestation: TlAttestationConfig(enabled: false, refreshInterval: 3600),
  );
}
