import 'dart:convert';

import 'package:tracelet/tracelet.dart';

/// Builds a single, copy-and-paste-friendly **bug report** that bundles
/// everything a maintainer needs to triage a Tracelet issue:
///
/// 1. The diagnostic [HealthCheck] (permissions, battery/OEM, sensors, device).
/// 2. The **location filter in force** (`Tracelet.getCurrentLocationTuning`)
///    beside the configured thresholds, so an auto-tune is distinguishable
///    from configuration that never reached the native processor.
/// 3. The **active configuration** (`Tracelet.activeConfig`) — with secrets
///    automatically redacted.
/// 4. The most recent **device logs** (`Tracelet.getLogs`).
/// 5. The most recent **telematics events** (`Tracelet.getTelematicsEvents`).
/// 6. The **geofence decision trace** — every `[geofence]`-tagged log line,
///    lifted into its own section so rare ENTER/EXIT transitions are not buried
///    by routine lifecycle chatter.
/// 7. The **session lifecycle trace** — what the background and killed-state
///    pipelines actually did (service and boot bootstrap outcomes on Android,
///    relaunch and termination boundaries on iOS, motion-state transitions on
///    both). Recorded regardless of `logLevel`, so a report carries it even
///    when the developer never enabled logging.
///
/// The output is GitHub-flavoured Markdown, ready to drop straight into an
/// issue. Every section is gathered defensively — if one source fails (e.g.
/// the plugin isn't initialized), that section reports the error instead of
/// failing the whole report.
///
/// ```dart
/// final report = await TraceletBugReport.build();
/// await Clipboard.setData(ClipboardData(text: report));
/// // or: await Share.share(report);
/// ```
class TraceletBugReport {
  TraceletBugReport._();

  /// Header keys (case-insensitive, substring match) whose values are masked
  /// before the configuration is included in the report. Prevents API keys,
  /// auth tokens, URLs and pinning material from leaking into a pasted issue.
  static const List<String> _sensitiveKeyHints = [
    'url',
    'header',
    'param',
    'extra',
    'token',
    'secret',
    'key',
    'password',
    'auth',
    'fingerprint',
    'certificate',
    'credential',
  ];

  /// Builds the full Markdown bug report.
  ///
  /// - [logLimit] — how many recent log entries to include (default 500).
  /// - [telematicsLimit] — how many recent telematics events to include
  ///   (default 100).
  /// - [appName] / [appVersion] — optional host-app identifiers shown in the
  ///   header (your `package_info_plus` values, for example).
  /// - [includeConfig] — set `false` to omit the configuration section.
  /// - [geofenceTraceLimit] — how many recent log entries to scan for the
  ///   geofence decision trace (default 5000). Scans deeper than [logLimit]
  ///   because transitions are rare and routine chatter can bury them.
  /// - [lifecycleTraceLimit] — how many recent log entries to scan for the
  ///   session lifecycle trace (default 5000), for the same reason.
  ///
  /// Both defaults were 2000, which is also the SDK's row cap at
  /// `logLevel: verbose` — so the scan could see the whole table and no more.
  /// The cap is now applied per channel, and the always-on `LIFECYCLE`
  /// rows are kept *behind* up to a full cap of level-based chatter; a 2000-row
  /// scan would now stop short of exactly the entries these sections exist to
  /// surface.
  static Future<String> build({
    int logLimit = 500,
    int telematicsLimit = 100,
    int geofenceTraceLimit = 5000,
    int lifecycleTraceLimit = 5000,
    String? appName,
    String? appVersion,
    bool includeConfig = true,
  }) async {
    final buffer = StringBuffer();
    final now = DateTime.now().toUtc().toIso8601String();

    buffer.writeln('# Tracelet Bug Report');
    buffer.writeln();
    buffer.writeln('_Generated by Tracelet Doctor at $now (UTC)._');
    buffer.writeln();
    // Which Tracelet produced this was, until #398, the first thing triage had
    // to ask and the one thing the report could not answer — least of all weeks
    // later, pasted into an issue.
    buffer.writeln('- **Tracelet:** $traceletVersion');
    if (appName != null || appVersion != null) {
      buffer.writeln('- **App:** ${appName ?? '—'} ${appVersion ?? ''}'.trim());
    }
    buffer.writeln();
    buffer.writeln(
      '> ⚠️ This report may include device and configuration '
      'details. Secrets (URLs, headers, keys) are redacted, but please '
      'review before sharing publicly.',
    );
    buffer.writeln();

    // One read, two sections. The health check's verdict has to account for
    // the foreground-service restrictions, and the two sections contradicting
    // each other is the failure this fixes — so they read the same snapshot.
    Map<String, Object?>? fgsHealth;
    Object? fgsHealthError;
    try {
      fgsHealth = await Tracelet.getForegroundServiceHealth();
    } catch (e) {
      fgsHealthError = e;
    }

    await _writeHealth(buffer, fgsHealth);
    _writeForegroundServiceHealth(buffer, fgsHealth, fgsHealthError);
    await _writeLocationTuning(buffer);
    if (includeConfig) _writeConfig(buffer);
    await _writeTelematics(buffer, telematicsLimit);

    // One read for all four log sections. They used to make four separate
    // `getLogs` calls — the same rows over the platform channel up to four
    // times — which is what kept the scan depth timid. Fetching the deepest
    // window once and slicing it costs less than the old 2000x4 did.
    final scanLimit = [
      logLimit,
      geofenceTraceLimit,
      lifecycleTraceLimit,
    ].reduce((a, b) => a > b ? a : b);
    List<LogEntry>? logs;
    Object? logsError;
    try {
      logs = await Tracelet.getLogs(scanLimit);
    } catch (e) {
      logsError = e;
    }

    _writeStreamHealth(buffer, logs, logsError, lifecycleTraceLimit);
    _writeLifecycleTrace(buffer, logs, logsError, lifecycleTraceLimit);
    _writeGeofenceTrace(buffer, logs, logsError, geofenceTraceLimit);
    _writeLogs(buffer, logs, logsError, logLimit);

    return buffer.toString();
  }

  // ---------------------------------------------------------------------------
  // Sections
  // ---------------------------------------------------------------------------

  static Future<void> _writeHealth(
    StringBuffer buffer,
    Map<String, Object?>? fgsHealth,
  ) async {
    buffer.writeln('## Health check');
    buffer.writeln();

    // Computed before the health call and reported after it either way. These
    // are the conditions under which background tracking cannot work at all,
    // and they come from the foreground-service snapshot — so a health call
    // that fails must not take them down with it. A report that degrades is
    // still a report; one that hides the blocker is worse than none (#406).
    final blockers = <String>[
      if (fgsHealth?['backgroundRestricted'] == true)
        'App is in the "Restricted" battery state — the OS blocks background service starts and foreground-service promotion (#406)',
      if (fgsHealth?['standbyBucketName'] == 'restricted')
        'App is in the RESTRICTED standby bucket — background work is heavily curtailed (#406)',
      if (fgsHealth?['locationCapabilityLikelyDenied'] == true)
        'Foreground service is promoted but denied the location capability — it was started from the background (#405)',
      if (fgsHealth?['lastForegroundPromotionResult'] == 'refused')
        'The OS refused the last foreground-service promotion (#406)',
    ];

    try {
      final health = await Tracelet.getHealth();
      buffer.writeln('| Field | Value |');
      buffer.writeln('|---|---|');
      buffer.writeln('| Platform | ${health.platform} |');
      buffer.writeln('| OS version | ${health.osVersion} |');
      buffer.writeln('| Manufacturer | ${health.manufacturer} |');
      buffer.writeln('| Model | ${health.model} |');
      buffer.writeln(
        '| Aggressive OEM | ${health.isAggressiveOem} '
        '(rating ${health.aggressionRating}/5) |',
      );
      buffer.writeln('| Tracking enabled | ${health.trackingEnabled} |');
      buffer.writeln('| Tracking mode | ${health.trackingMode.name} |');
      buffer.writeln('| Is moving | ${health.isMoving} |');
      buffer.writeln(
        '| Odometer (m) | ${health.odometer.toStringAsFixed(1)} |',
      );
      buffer.writeln(
        '| Location permission | ${health.locationPermission.name} |',
      );
      // Name, not the raw index. `Motion permission | 0` in a bug report is
      // ambiguous — it reads as a boolean or a count, and it can't be checked
      // against the enum without opening the source. Keep the index alongside
      // it since the field is still an int on the wire.
      buffer.writeln(
        '| Motion permission | '
        '${health.motionAuthorization?.name ?? 'unknown'} '
        '(${health.motionPermission}) |',
      );
      buffer.writeln('| Accuracy | ${health.accuracyAuthorization.name} |');
      buffer.writeln(
        '| Location services | ${health.locationServicesEnabled} |',
      );
      buffer.writeln('| Power save mode | ${health.isPowerSaveMode} |');
      buffer.writeln(
        '| Ignoring battery opt | ${health.isIgnoringBatteryOptimizations} |',
      );
      buffer.writeln('| Accelerometer | ${health.hasAccelerometer} |');
      buffer.writeln('| Gyroscope | ${health.hasGyroscope} |');
      buffer.writeln('| Magnetometer | ${health.hasMagnetometer} |');
      buffer.writeln('| Significant motion | ${health.hasSignificantMotion} |');
      buffer.writeln('| Mock locations | ${health.mockLocationsDetected} |');
      buffer.writeln('| Pending locations | ${health.locationCount} |');
      buffer.writeln();

      // `HealthCheck.warnings` is computed from the health map alone, and the
      // background restrictions live in the foreground-service snapshot — a
      // different native call. So this section reported "all systems healthy"
      // on a device where the OS had switched background tracking off
      // outright, with the contradiction sitting one section below. A blocker
      // named anywhere in the report must not be missing from the verdict at
      // the top of it (#406, #405).
      _writeVerdict(buffer, health.warnings, blockers);
    } catch (e) {
      buffer.writeln('_Could not read health: ${e}_');
      buffer.writeln();
      _writeVerdict(buffer, const <HealthWarning>[], blockers);
    }
    buffer.writeln();
  }

  /// Writes the health verdict: blockers first, then degradations.
  ///
  /// Blockers stop background tracking outright; warnings degrade it. Ordering
  /// them together under one count keeps the reader from concluding "healthy"
  /// off the first line while the thing that broke tracking sits further down.
  static void _writeVerdict(
    StringBuffer buffer,
    List<HealthWarning> warnings,
    List<String> blockers,
  ) {
    if (warnings.isEmpty && blockers.isEmpty) {
      buffer.writeln('**Warnings:** none — all systems healthy. ✅');
      return;
    }
    buffer.writeln('**Warnings (${warnings.length + blockers.length}):**');
    buffer.writeln();
    for (final b in blockers) {
      buffer.writeln('- 🔴 $b');
    }
    for (final w in warnings) {
      buffer.writeln('- ⚠️ ${w.description}');
    }
  }

  static void _writeForegroundServiceHealth(
    StringBuffer buffer,
    Map<String, Object?>? health,
    Object? error,
  ) {
    buffer.writeln('## Foreground service health');
    buffer.writeln();
    if (health == null) {
      buffer.writeln('_Could not read foreground-service health: ${error}_');
      buffer.writeln();
      return;
    }
    {
      buffer.writeln('| Field | Value |');
      buffer.writeln('|---|---|');
      buffer.writeln('| Platform | ${health['platform']} |');
      buffer.writeln('| Desired (enabled) | ${health['desiredEnabled']} |');
      buffer.writeln(
        '| FGS configured | ${health['foregroundServiceEnabled']} |',
      );
      buffer.writeln('| Service running | ${health['serviceRunning']} |');
      buffer.writeln(
        '| Promoted to foreground | ${health['serviceForeground']} |',
      );
      buffer.writeln(
        '| Notification id | ${health['foregroundNotificationId']} |',
      );
      buffer.writeln(
        '| Last promotion result '
        '| ${health['lastForegroundPromotionResult']} |',
      );
      buffer.writeln(
        '| Last promotion failure class '
        '| ${health['lastForegroundPromotionFailureClass']} |',
      );
      buffer.writeln(
        '| Last promotion failure message '
        '| ${health['lastForegroundPromotionFailureMessage']} |',
      );
      buffer.writeln(
        '| Last transition (ms) '
        '| ${health['lastForegroundTransitionAt']} |',
      );
      buffer.writeln(
        '| Started in foreground '
        '| ${health['serviceStartedInForeground']} |',
      );
      buffer.writeln(
        '| Background restricted | ${health['backgroundRestricted']} |',
      );
      buffer.writeln(
        '| Standby bucket '
        '| ${health['standbyBucketName']} (${health['standbyBucket']}) |',
      );
      buffer.writeln();
      _writeForegroundServiceVerdict(buffer, health);
    }
    buffer.writeln();
  }

  /// States, in words, whether the foreground service can actually track.
  ///
  /// The table above is every field a maintainer needs and none of the
  /// conclusion. A service that is promoted, running, carrying
  /// `FOREGROUND_SERVICE_TYPE_LOCATION` and denied location by the OS renders as
  /// six green rows (#405), which is how a report from a device that had
  /// recorded nothing for 52 seconds read as healthy. So the report draws the
  /// conclusion itself rather than leaving it to be inferred from a row that
  /// says `true`.
  static void _writeForegroundServiceVerdict(
    StringBuffer buffer,
    Map<String, Object?> health,
  ) {
    final findings = <String>[];

    if (health['locationCapabilityLikelyDenied'] == true) {
      findings.add(
        '🔴 **The foreground service is promoted but cannot use location.** It '
        'was started while the app was in the background, and Android denies a '
        'background-started foreground service the location capability for the '
        "service's entire life — regardless of manifest "
        '`foregroundServiceType`, `ACCESS_BACKGROUND_LOCATION`, or the Doze '
        'allowlist. The notification shows and no fix will arrive. Tracking '
        'recovers only when the service is re-created from the foreground, '
        'i.e. the next time the app is opened. (#405)',
      );
    }

    if (health['backgroundRestricted'] == true) {
      findings.add(
        '🔴 **The app is in the "Restricted" battery state** (Forced App '
        'Standby). The OS blocks background service starts and '
        'foreground-service promotion outright. This is independent of the '
        'battery-optimization exemption reported in the health check above, '
        'which may well say `true` at the same time. Fix: Settings → Apps → '
        'this app → Battery → Unrestricted. (#406)',
      );
    }

    if (health['standbyBucketName'] == 'restricted') {
      findings.add(
        '⚠️ The app is in the `restricted` standby bucket, so jobs and alarms '
        'are heavily deferred.',
      );
    }

    if (findings.isEmpty) {
      buffer.writeln(
        '**Verdict:** no foreground-service restriction detected. Note this '
        'covers promotion and location capability only — see the stream-health '
        'section for whether fixes are actually arriving.',
      );
      return;
    }
    buffer.writeln('**Verdict:**');
    buffer.writeln();
    for (final f in findings) {
      buffer.writeln('- $f');
      buffer.writeln();
    }
  }

  /// Writes the location-filter thresholds **actually in force**, next to the
  /// configured ones.
  ///
  /// The `## Active configuration` section below is a Dart-side mirror of the
  /// last `Config` passed in — it cannot show a transport-mode auto-tune, and
  /// it cannot show a configured value that never reached the native processor.
  /// Both look identical in a config dump and produce very different bug
  /// reports, so the two columns are worth the space.
  static Future<void> _writeLocationTuning(StringBuffer buffer) async {
    buffer.writeln('## Location filter (in force vs. configured)');
    buffer.writeln();
    try {
      final autoTune =
          Tracelet.activeConfig.classifier.autoTuneFromTransportMode;
      buffer.writeln('- **Auto-tune from transport mode:** $autoTune');
      buffer.writeln();

      final tuning = await Tracelet.getCurrentLocationTuning();
      if (tuning == null) {
        buffer.writeln(
          '_No location processor — tracking has not run in this process '
          '(or this is web, which has no equivalent filter state)._',
        );
      } else {
        final geo = Tracelet.activeConfig.geo;
        final filter = geo.filter;
        buffer.writeln('| Threshold | Configured | In force |');
        buffer.writeln('|---|---|---|');
        buffer.writeln(
          '| Distance filter (m) | ${geo.distanceFilter} '
          '| ${tuning.distanceFilter} |',
        );
        buffer.writeln(
          '| Tracking accuracy (m) | ${filter.trackingAccuracyThreshold} '
          '| ${tuning.trackingAccuracyThreshold} |',
        );
        buffer.writeln(
          '| Odometer accuracy (m) | ${filter.odometerAccuracyThreshold} '
          '| ${tuning.odometerAccuracyThreshold} |',
        );
        buffer.writeln(
          '| Max implied speed (m/s) | ${filter.maxImpliedSpeed} '
          '| ${tuning.maxImpliedSpeed} |',
        );
        buffer.writeln();
        final drifted =
            geo.distanceFilter != tuning.distanceFilter ||
            filter.trackingAccuracyThreshold !=
                tuning.trackingAccuracyThreshold ||
            filter.odometerAccuracyThreshold !=
                tuning.odometerAccuracyThreshold ||
            filter.maxImpliedSpeed != tuning.maxImpliedSpeed;
        if (drifted) {
          buffer.writeln(
            autoTune
                ? '⚙️ The columns differ because a committed transport mode is '
                      'auto-tuning the filter.'
                : '⚠️ The columns differ with auto-tuning **off** — configured '
                      'values are not reaching the native processor.',
          );
        }
      }
    } catch (e) {
      buffer.writeln('_Could not read the location tuning: ${e}_');
    }
    buffer.writeln();
  }

  static void _writeConfig(StringBuffer buffer) {
    buffer.writeln('## Active configuration');
    buffer.writeln();
    try {
      final raw = Tracelet.activeConfig.toMap();
      final redacted = redactConfig(raw);
      final json = const JsonEncoder.withIndent('  ').convert(redacted);
      buffer.writeln('```json');
      buffer.writeln(json);
      buffer.writeln('```');
    } catch (e) {
      buffer.writeln('_Could not read configuration: ${e}_');
    }
    buffer.writeln();
  }

  static Future<void> _writeTelematics(StringBuffer buffer, int limit) async {
    buffer.writeln('## Telematics events (most recent)');
    buffer.writeln();
    try {
      final events = await Tracelet.getTelematicsEvents(limit);
      if (events.isEmpty) {
        buffer.writeln('_No stored telematics events._');
      } else {
        buffer.writeln('| Type | Severity | Lat | Lng | Time | Synced |');
        buffer.writeln('|---|---|---|---|---|---|');
        for (final e in events) {
          buffer.writeln(
            '| ${e.eventType} | ${e.severity.toStringAsFixed(2)} '
            '| ${e.latitude.toStringAsFixed(5)} '
            '| ${e.longitude.toStringAsFixed(5)} '
            '| ${e.timestamp} | ${e.synced} |',
          );
        }
      }
    } catch (e) {
      buffer.writeln('_Could not read telematics events: ${e}_');
    }
    buffer.writeln();
  }

  /// Writes the session lifecycle trace: every `LIFECYCLE`-level log line,
  /// pulled out of the general log stream into its own section (#318).
  ///
  /// These entries are the SDK's account of what its background and
  /// killed-state pipelines actually did — the `session: start` / `session:
  /// stop` boundaries and the mode and strategy each session ran with on both
  /// platforms, plus service create/destroy and sticky restarts and boot
  /// bootstrap outcomes on Android, relaunch and termination boundaries on iOS,
  /// and motion-state transitions on both. They are written regardless of
  /// `logLevel`, precisely because the failures they explain cannot be
  /// reproduced on demand with logging turned up first.
  ///
  /// Given its own section for the same reason as the geofence trace: lifecycle
  /// events are rare (a handful per session) while routine chatter is not, so
  /// at `debug`/`verbose` the entry from the overnight run that actually failed
  /// is exactly the one pushed out of the `## Logs` window. Scanning deeper and
  /// keeping only these lines makes the report answer the question it was
  /// generated for.
  ///
  /// **Reading it:** an absent entry is as informative as a present one. Start
  /// with the session boundaries on both platforms: a `session: stop` with
  /// nothing after it means tracking was stopped and never restarted, which is
  /// the ordinary explanation for "it stopped tracking" and the first thing to
  /// rule out (`restart=true` marks setConfig()'s in-place restart, which is
  /// always followed by a start and is not the session ending). On
  /// Android, `motion (foreground)` lines with no `motion (killed-state, …)`
  /// counterpart mean the background detector never ran; no
  /// `boot-tracking: bootstrapping` means the pipeline never came up. On iOS, a
  /// `termination:` line with no `relaunch:` after it means the app was never
  /// relaunched — expected after a user force-quit, a bug otherwise — and a
  /// `relaunch: declined to resume` line names the precondition that failed.
  static void _writeLifecycleTrace(
    StringBuffer buffer,
    List<LogEntry>? logs,
    Object? error,
    int limit,
  ) {
    buffer.writeln('## Session lifecycle (background & killed-state trace)');
    buffer.writeln();
    if (logs == null) {
      buffer.writeln('_Could not read the lifecycle trace: ${error}_');
    } else {
      final trace = logs
          .take(limit)
          .where((log) => log.level.toUpperCase() == 'LIFECYCLE')
          .toList();
      if (trace.isEmpty) {
        buffer.writeln('_No lifecycle events in the last $limit log entries._');
      } else {
        buffer.writeln('```');
        for (final log in trace) {
          buffer.writeln('${log.timestamp} ${log.message}');
        }
        buffer.writeln('```');
      }
    }
    buffer.writeln();
  }

  /// Log lines the stream-health section lifts out of the general log.
  ///
  /// All of them are written on the always-on lifecycle channel, so they survive
  /// a released app's default `logLevel` — which is the point: the failures they
  /// describe are the ones nobody can reproduce on demand (#397).
  static const List<String> _streamHealthMarkers = [
    'location stream stalled',
    'location stream recovered',
    // #407: silence is a different fault from rejection, and until it was
    // announced on its own timer a stream delivering nothing produced no marker
    // at all — so this section reported it as health.
    'location stream silent',
    'location stream resumed',
    'battery budget:',
    'anchor re-seeded',
    'adaptive sampling held',
  ];

  /// Writes what happened to the location stream: stalls, recoveries, and every
  /// battery-budget throttle movement.
  ///
  /// These answer the question a frozen map actually poses — *is tracking
  /// running and rejecting everything, or not running at all?* — which nothing
  /// in the report could distinguish before. A stalled stream and a parked
  /// device produce identical output everywhere else, and telling them apart
  /// took two exports and a source read the first time it came up (#393, #394).
  ///
  /// Each stall line carries the rejection histogram, the gate the last fix was
  /// measured against, the configured gate beside it, and the thresholds in
  /// force. Each budget line carries the rung, the drain that justified it, and
  /// the resolution of the measurement that produced the drain — so a throttle
  /// fired on quantization noise is visible as such.
  static void _writeStreamHealth(
    StringBuffer buffer,
    List<LogEntry>? logs,
    Object? error,
    int limit,
  ) {
    buffer.writeln('## Location stream health (stalls & battery budget)');
    buffer.writeln();
    if (logs == null) {
      buffer.writeln('_Could not read the stream-health trace: ${error}_');
    } else {
      final trace = logs
          .take(limit)
          .where((log) => _streamHealthMarkers.any(log.message.contains))
          .toList();
      if (trace.isEmpty) {
        // Deliberately not "the stream has been accepting fixes". It said that
        // over a 52-second window in which it accepted nothing, because the
        // only watchdog was fix-driven and silence never reached it (#405,
        // #407). The absence of markers is the absence of markers.
        buffer.writeln(
          '_No stall, silence or battery-budget entries in the last $limit log '
          'entries. That means none were recorded — check the lifecycle trace '
          'and the fix timestamps above before reading it as health._',
        );
      } else {
        buffer.writeln('```');
        for (final log in trace) {
          buffer.writeln('${log.timestamp} ${log.message}');
        }
        buffer.writeln('```');
      }
    }
    buffer.writeln();
  }

  /// Writes the geofence decision trace: every `[geofence]`-tagged log line,
  /// pulled out of the general log stream into its own section.
  ///
  /// Geofence transitions are rare (a handful a day) while routine lifecycle
  /// chatter is not, so in a busy app the crossings get pushed out of the
  /// `## Logs` window before anyone generates a report. This section scans
  /// deeper than that window and keeps only the geofence lines, so an
  /// ENTER/EXIT and its decision inputs survive even when the general log is
  /// saturated.
  ///
  /// Each transition line carries the distance, radius, hysteresis buffer,
  /// exit threshold, and both the raw and post-clamp accuracy, which is what
  /// distinguishes a genuine departure from a drift-induced false EXIT.
  static void _writeGeofenceTrace(
    StringBuffer buffer,
    List<LogEntry>? logs,
    Object? error,
    int limit,
  ) {
    buffer.writeln('## Geofence transitions (decision trace)');
    buffer.writeln();
    if (logs == null) {
      buffer.writeln('_Could not read the geofence trace: ${error}_');
    } else {
      final trace = logs
          .take(limit)
          .where((log) => log.message.contains('[geofence]'))
          .toList();
      if (trace.isEmpty) {
        buffer.writeln(
          '_No geofence activity in the last $limit log entries._',
        );
      } else {
        buffer.writeln('```');
        for (final log in trace) {
          buffer.writeln(
            '${log.timestamp} [${log.level.toUpperCase()}] ${log.message}',
          );
        }
        buffer.writeln('```');
      }
    }
    buffer.writeln();
  }

  static void _writeLogs(
    StringBuffer buffer,
    List<LogEntry>? allLogs,
    Object? error,
    int limit,
  ) {
    buffer.writeln('## Logs (last $limit)');
    buffer.writeln();
    if (allLogs == null) {
      buffer.writeln('_Could not read logs: ${error}_');
    } else {
      final logs = allLogs.take(limit).toList();
      if (logs.isEmpty) {
        buffer.writeln('_No logs recorded._');
      } else {
        buffer.writeln('```');
        for (final log in logs) {
          buffer.writeln(
            '${log.timestamp} [${log.level.toUpperCase()}] ${log.message}',
          );
        }
        buffer.writeln('```');
      }
    }
    buffer.writeln();
  }

  // ---------------------------------------------------------------------------
  // Redaction
  // ---------------------------------------------------------------------------

  /// Returns a deep copy of [config] with the values of any secret-looking
  /// keys (URLs, headers, params, keys, tokens, pinning material) replaced by
  /// `«redacted»`. Exposed so apps can safely log or display their own config.
  static Map<String, Object?> redactConfig(Map<String, Object?> config) =>
      (_redact(config)! as Map).cast<String, Object?>();

  /// Recursively masks the values of any key whose name hints at a secret.
  static Object? _redact(Object? value) {
    if (value is Map) {
      final out = <String, Object?>{};
      value.forEach((k, v) {
        final key = k.toString();
        if (_isSensitive(key) && v != null) {
          out[key] = '«redacted»';
        } else {
          out[key] = _redact(v);
        }
      });
      return out;
    }
    if (value is List) {
      return value.map(_redact).toList();
    }
    return value;
  }

  static bool _isSensitive(String key) {
    final lower = key.toLowerCase();
    return _sensitiveKeyHints.any(lower.contains);
  }
}
