import 'dart:convert';

import 'package:tracelet/tracelet.dart';

/// Builds a single, copy-and-paste-friendly **bug report** that bundles
/// everything a maintainer needs to triage a Tracelet issue:
///
/// 1. The diagnostic [HealthCheck] (permissions, battery/OEM, sensors, device).
/// 2. The **location filter in force** (`Tracelet.getCurrentLocationTuning`)
///    beside the configured thresholds, so an auto-tune is distinguishable
///    from configuration that never reached the native processor.
/// 3. The **active configuration** (`Tracelet.activeConfig`) — with secrets
///    automatically redacted.
/// 4. The most recent **device logs** (`Tracelet.getLogs`).
/// 5. The most recent **telematics events** (`Tracelet.getTelematicsEvents`).
/// 6. The **geofence decision trace** — every `[geofence]`-tagged log line,
///    lifted into its own section so rare ENTER/EXIT transitions are not buried
///    by routine lifecycle chatter.
/// 7. The **session lifecycle trace** — what the background and killed-state
///    pipelines actually did (service and boot bootstrap outcomes on Android,
///    relaunch and termination boundaries on iOS, motion-state transitions on
///    both). Recorded regardless of `logLevel`, so a report carries it even
///    when the developer never enabled logging.
///
/// The output is GitHub-flavoured Markdown, ready to drop straight into an
/// issue. Every section is gathered defensively — if one source fails (e.g.
/// the plugin isn't initialized), that section reports the error instead of
/// failing the whole report.
///
/// ```dart
/// final report = await TraceletBugReport.build();
/// await Clipboard.setData(ClipboardData(text: report));
/// // or: await Share.share(report);
/// ```
class TraceletBugReport {
  TraceletBugReport._();

  /// Header keys (case-insensitive, substring match) whose values are masked
  /// before the configuration is included in the report. Prevents API keys,
  /// auth tokens, URLs and pinning material from leaking into a pasted issue.
  static const List<String> _sensitiveKeyHints = [
    'url',
    'header',
    'param',
    'extra',
    'token',
    'secret',
    'key',
    'password',
    'auth',
    'fingerprint',
    'certificate',
    'credential',
  ];

  /// Builds the full Markdown bug report.
  ///
  /// - [logLimit] — how many recent log entries to include (default 500).
  /// - [telematicsLimit] — how many recent telematics events to include
  ///   (default 100).
  /// - [appName] / [appVersion] — optional host-app identifiers shown in the
  ///   header (your `package_info_plus` values, for example).
  /// - [includeConfig] — set `false` to omit the configuration section.
  /// - [geofenceTraceLimit] — how many recent log entries to scan for the
  ///   geofence decision trace (default 2000). Scans deeper than [logLimit]
  ///   because transitions are rare and routine chatter can bury them.
  /// - [lifecycleTraceLimit] — how many recent log entries to scan for the
  ///   session lifecycle trace (default 2000), for the same reason.
  static Future<String> build({
    int logLimit = 500,
    int telematicsLimit = 100,
    int geofenceTraceLimit = 2000,
    int lifecycleTraceLimit = 2000,
    String? appName,
    String? appVersion,
    bool includeConfig = true,
  }) async {
    final buffer = StringBuffer();
    final now = DateTime.now().toUtc().toIso8601String();

    buffer.writeln('# Tracelet Bug Report');
    buffer.writeln();
    buffer.writeln('_Generated by Tracelet Doctor at $now (UTC)._');
    if (appName != null || appVersion != null) {
      buffer.writeln();
      buffer.writeln('- **App:** ${appName ?? '—'} ${appVersion ?? ''}'.trim());
    }
    buffer.writeln();
    buffer.writeln(
      '> ⚠️ This report may include device and configuration '
      'details. Secrets (URLs, headers, keys) are redacted, but please '
      'review before sharing publicly.',
    );
    buffer.writeln();

    await _writeHealth(buffer);
    await _writeForegroundServiceHealth(buffer);
    await _writeLocationTuning(buffer);
    if (includeConfig) _writeConfig(buffer);
    await _writeTelematics(buffer, telematicsLimit);
    await _writeLifecycleTrace(buffer, lifecycleTraceLimit);
    await _writeGeofenceTrace(buffer, geofenceTraceLimit);
    await _writeLogs(buffer, logLimit);

    return buffer.toString();
  }

  // ---------------------------------------------------------------------------
  // Sections
  // ---------------------------------------------------------------------------

  static Future<void> _writeHealth(StringBuffer buffer) async {
    buffer.writeln('## Health check');
    buffer.writeln();
    try {
      final health = await Tracelet.getHealth();
      buffer.writeln('| Field | Value |');
      buffer.writeln('|---|---|');
      buffer.writeln('| Platform | ${health.platform} |');
      buffer.writeln('| OS version | ${health.osVersion} |');
      buffer.writeln('| Manufacturer | ${health.manufacturer} |');
      buffer.writeln('| Model | ${health.model} |');
      buffer.writeln(
        '| Aggressive OEM | ${health.isAggressiveOem} '
        '(rating ${health.aggressionRating}/5) |',
      );
      buffer.writeln('| Tracking enabled | ${health.trackingEnabled} |');
      buffer.writeln('| Tracking mode | ${health.trackingMode.name} |');
      buffer.writeln('| Is moving | ${health.isMoving} |');
      buffer.writeln(
        '| Odometer (m) | ${health.odometer.toStringAsFixed(1)} |',
      );
      buffer.writeln(
        '| Location permission | ${health.locationPermission.name} |',
      );
      // Name, not the raw index. `Motion permission | 0` in a bug report is
      // ambiguous — it reads as a boolean or a count, and it can't be checked
      // against the enum without opening the source. Keep the index alongside
      // it since the field is still an int on the wire.
      buffer.writeln(
        '| Motion permission | '
        '${health.motionAuthorization?.name ?? 'unknown'} '
        '(${health.motionPermission}) |',
      );
      buffer.writeln('| Accuracy | ${health.accuracyAuthorization.name} |');
      buffer.writeln(
        '| Location services | ${health.locationServicesEnabled} |',
      );
      buffer.writeln('| Power save mode | ${health.isPowerSaveMode} |');
      buffer.writeln(
        '| Ignoring battery opt | ${health.isIgnoringBatteryOptimizations} |',
      );
      buffer.writeln('| Accelerometer | ${health.hasAccelerometer} |');
      buffer.writeln('| Gyroscope | ${health.hasGyroscope} |');
      buffer.writeln('| Magnetometer | ${health.hasMagnetometer} |');
      buffer.writeln('| Significant motion | ${health.hasSignificantMotion} |');
      buffer.writeln('| Mock locations | ${health.mockLocationsDetected} |');
      buffer.writeln('| Pending locations | ${health.locationCount} |');
      buffer.writeln();

      if (health.warnings.isEmpty) {
        buffer.writeln('**Warnings:** none — all systems healthy. ✅');
      } else {
        buffer.writeln('**Warnings (${health.warnings.length}):**');
        buffer.writeln();
        for (final w in health.warnings) {
          buffer.writeln('- ⚠️ ${w.description}');
        }
      }
    } catch (e) {
      buffer.writeln('_Could not read health: ${e}_');
    }
    buffer.writeln();
  }

  static Future<void> _writeForegroundServiceHealth(StringBuffer buffer) async {
    buffer.writeln('## Foreground service health');
    buffer.writeln();
    try {
      final health = await Tracelet.getForegroundServiceHealth();
      buffer.writeln('| Field | Value |');
      buffer.writeln('|---|---|');
      buffer.writeln('| Platform | ${health['platform']} |');
      buffer.writeln('| Desired (enabled) | ${health['desiredEnabled']} |');
      buffer.writeln(
        '| FGS configured | ${health['foregroundServiceEnabled']} |',
      );
      buffer.writeln('| Service running | ${health['serviceRunning']} |');
      buffer.writeln(
        '| Promoted to foreground | ${health['serviceForeground']} |',
      );
      buffer.writeln(
        '| Notification id | ${health['foregroundNotificationId']} |',
      );
      buffer.writeln(
        '| Last promotion result '
        '| ${health['lastForegroundPromotionResult']} |',
      );
      buffer.writeln(
        '| Last promotion failure class '
        '| ${health['lastForegroundPromotionFailureClass']} |',
      );
      buffer.writeln(
        '| Last promotion failure message '
        '| ${health['lastForegroundPromotionFailureMessage']} |',
      );
      buffer.writeln(
        '| Last transition (ms) '
        '| ${health['lastForegroundTransitionAt']} |',
      );
    } catch (e) {
      buffer.writeln('_Could not read foreground-service health: ${e}_');
    }
    buffer.writeln();
  }

  /// Writes the location-filter thresholds **actually in force**, next to the
  /// configured ones.
  ///
  /// The `## Active configuration` section below is a Dart-side mirror of the
  /// last `Config` passed in — it cannot show a transport-mode auto-tune, and
  /// it cannot show a configured value that never reached the native processor.
  /// Both look identical in a config dump and produce very different bug
  /// reports, so the two columns are worth the space.
  static Future<void> _writeLocationTuning(StringBuffer buffer) async {
    buffer.writeln('## Location filter (in force vs. configured)');
    buffer.writeln();
    try {
      final autoTune =
          Tracelet.activeConfig.classifier.autoTuneFromTransportMode;
      buffer.writeln('- **Auto-tune from transport mode:** $autoTune');
      buffer.writeln();

      final tuning = await Tracelet.getCurrentLocationTuning();
      if (tuning == null) {
        buffer.writeln(
          '_No location processor — tracking has not run in this process '
          '(or this is web, which has no equivalent filter state)._',
        );
      } else {
        final geo = Tracelet.activeConfig.geo;
        final filter = geo.filter;
        buffer.writeln('| Threshold | Configured | In force |');
        buffer.writeln('|---|---|---|');
        buffer.writeln(
          '| Distance filter (m) | ${geo.distanceFilter} '
          '| ${tuning.distanceFilter} |',
        );
        buffer.writeln(
          '| Tracking accuracy (m) | ${filter.trackingAccuracyThreshold} '
          '| ${tuning.trackingAccuracyThreshold} |',
        );
        buffer.writeln(
          '| Odometer accuracy (m) | ${filter.odometerAccuracyThreshold} '
          '| ${tuning.odometerAccuracyThreshold} |',
        );
        buffer.writeln(
          '| Max implied speed (m/s) | ${filter.maxImpliedSpeed} '
          '| ${tuning.maxImpliedSpeed} |',
        );
        buffer.writeln();
        final drifted =
            geo.distanceFilter != tuning.distanceFilter ||
            filter.trackingAccuracyThreshold !=
                tuning.trackingAccuracyThreshold ||
            filter.odometerAccuracyThreshold !=
                tuning.odometerAccuracyThreshold ||
            filter.maxImpliedSpeed != tuning.maxImpliedSpeed;
        if (drifted) {
          buffer.writeln(
            autoTune
                ? '⚙️ The columns differ because a committed transport mode is '
                      'auto-tuning the filter.'
                : '⚠️ The columns differ with auto-tuning **off** — configured '
                      'values are not reaching the native processor.',
          );
        }
      }
    } catch (e) {
      buffer.writeln('_Could not read the location tuning: ${e}_');
    }
    buffer.writeln();
  }

  static void _writeConfig(StringBuffer buffer) {
    buffer.writeln('## Active configuration');
    buffer.writeln();
    try {
      final raw = Tracelet.activeConfig.toMap();
      final redacted = redactConfig(raw);
      final json = const JsonEncoder.withIndent('  ').convert(redacted);
      buffer.writeln('```json');
      buffer.writeln(json);
      buffer.writeln('```');
    } catch (e) {
      buffer.writeln('_Could not read configuration: ${e}_');
    }
    buffer.writeln();
  }

  static Future<void> _writeTelematics(StringBuffer buffer, int limit) async {
    buffer.writeln('## Telematics events (most recent)');
    buffer.writeln();
    try {
      final events = await Tracelet.getTelematicsEvents(limit);
      if (events.isEmpty) {
        buffer.writeln('_No stored telematics events._');
      } else {
        buffer.writeln('| Type | Severity | Lat | Lng | Time | Synced |');
        buffer.writeln('|---|---|---|---|---|---|');
        for (final e in events) {
          buffer.writeln(
            '| ${e.eventType} | ${e.severity.toStringAsFixed(2)} '
            '| ${e.latitude.toStringAsFixed(5)} '
            '| ${e.longitude.toStringAsFixed(5)} '
            '| ${e.timestamp} | ${e.synced} |',
          );
        }
      }
    } catch (e) {
      buffer.writeln('_Could not read telematics events: ${e}_');
    }
    buffer.writeln();
  }

  /// Writes the session lifecycle trace: every `LIFECYCLE`-level log line,
  /// pulled out of the general log stream into its own section (#318).
  ///
  /// These entries are the SDK's account of what its background and
  /// killed-state pipelines actually did — service start/stop and sticky
  /// restarts and boot bootstrap outcomes on Android, relaunch and termination
  /// boundaries on iOS, and motion-state transitions on both. They are written
  /// regardless of `logLevel`, precisely because the failures they explain
  /// cannot be reproduced on demand with logging turned up first.
  ///
  /// Given its own section for the same reason as the geofence trace: lifecycle
  /// events are rare (a handful per session) while routine chatter is not, so
  /// at `debug`/`verbose` the entry from the overnight run that actually failed
  /// is exactly the one pushed out of the `## Logs` window. Scanning deeper and
  /// keeping only these lines makes the report answer the question it was
  /// generated for.
  ///
  /// **Reading it:** an absent entry is as informative as a present one. On
  /// Android, `motion (foreground)` lines with no `motion (killed-state, …)`
  /// counterpart mean the background detector never ran; no
  /// `boot-tracking: bootstrapping` means the pipeline never came up. On iOS, a
  /// `termination:` line with no `relaunch:` after it means the app was never
  /// relaunched — expected after a user force-quit, a bug otherwise — and a
  /// `relaunch: declined to resume` line names the precondition that failed.
  static Future<void> _writeLifecycleTrace(
    StringBuffer buffer,
    int limit,
  ) async {
    buffer.writeln('## Session lifecycle (background & killed-state trace)');
    buffer.writeln();
    try {
      final logs = await Tracelet.getLogs(limit);
      final trace = logs
          .where((log) => log.level.toUpperCase() == 'LIFECYCLE')
          .toList();
      if (trace.isEmpty) {
        buffer.writeln('_No lifecycle events in the last $limit log entries._');
      } else {
        buffer.writeln('```');
        for (final log in trace) {
          buffer.writeln('${log.timestamp} ${log.message}');
        }
        buffer.writeln('```');
      }
    } catch (e) {
      buffer.writeln('_Could not read the lifecycle trace: ${e}_');
    }
    buffer.writeln();
  }

  /// Writes the geofence decision trace: every `[geofence]`-tagged log line,
  /// pulled out of the general log stream into its own section.
  ///
  /// Geofence transitions are rare (a handful a day) while routine lifecycle
  /// chatter is not, so in a busy app the crossings get pushed out of the
  /// `## Logs` window before anyone generates a report. This section scans
  /// deeper than that window and keeps only the geofence lines, so an
  /// ENTER/EXIT and its decision inputs survive even when the general log is
  /// saturated.
  ///
  /// Each transition line carries the distance, radius, hysteresis buffer,
  /// exit threshold, and both the raw and post-clamp accuracy, which is what
  /// distinguishes a genuine departure from a drift-induced false EXIT.
  static Future<void> _writeGeofenceTrace(
    StringBuffer buffer,
    int limit,
  ) async {
    buffer.writeln('## Geofence transitions (decision trace)');
    buffer.writeln();
    try {
      final logs = await Tracelet.getLogs(limit);
      final trace = logs
          .where((log) => log.message.contains('[geofence]'))
          .toList();
      if (trace.isEmpty) {
        buffer.writeln(
          '_No geofence activity in the last $limit log entries._',
        );
      } else {
        buffer.writeln('```');
        for (final log in trace) {
          buffer.writeln(
            '${log.timestamp} [${log.level.toUpperCase()}] ${log.message}',
          );
        }
        buffer.writeln('```');
      }
    } catch (e) {
      buffer.writeln('_Could not read the geofence trace: ${e}_');
    }
    buffer.writeln();
  }

  static Future<void> _writeLogs(StringBuffer buffer, int limit) async {
    buffer.writeln('## Logs (last $limit)');
    buffer.writeln();
    try {
      final logs = await Tracelet.getLogs(limit);
      if (logs.isEmpty) {
        buffer.writeln('_No logs recorded._');
      } else {
        buffer.writeln('```');
        for (final log in logs) {
          buffer.writeln(
            '${log.timestamp} [${log.level.toUpperCase()}] ${log.message}',
          );
        }
        buffer.writeln('```');
      }
    } catch (e) {
      buffer.writeln('_Could not read logs: ${e}_');
    }
    buffer.writeln();
  }

  // ---------------------------------------------------------------------------
  // Redaction
  // ---------------------------------------------------------------------------

  /// Returns a deep copy of [config] with the values of any secret-looking
  /// keys (URLs, headers, params, keys, tokens, pinning material) replaced by
  /// `«redacted»`. Exposed so apps can safely log or display their own config.
  static Map<String, Object?> redactConfig(Map<String, Object?> config) =>
      (_redact(config)! as Map).cast<String, Object?>();

  /// Recursively masks the values of any key whose name hints at a secret.
  static Object? _redact(Object? value) {
    if (value is Map) {
      final out = <String, Object?>{};
      value.forEach((k, v) {
        final key = k.toString();
        if (_isSensitive(key) && v != null) {
          out[key] = '«redacted»';
        } else {
          out[key] = _redact(v);
        }
      });
      return out;
    }
    if (value is List) {
      return value.map(_redact).toList();
    }
    return value;
  }

  static bool _isSensitive(String key) {
    final lower = key.toLowerCase();
    return _sensitiveKeyHints.any(lower.contains);
  }
}
