import DocLayout from '../../../components/DocLayout'
import { getPageMap } from 'nextra/page-map'
import versions from '../../../versions.json'

// Frozen documentation archive — generated by scripts/version-cut.js from v3.7.6.
// Do not edit by hand and do not translate: see versions.json for why.
export default async function ArchivedLayout({ children }: { children: React.ReactNode }) {
  const pageMap = await getPageMap('/en/v3.7')
  const archive = versions.archived.find(v => v.slug === 'v3.7')
  return (
    <DocLayout
      pageMap={pageMap}
      version={archive ? archive.label : '3.7.6'}
      locale="en"
      archivedSlug="v3.7"
    >
      {children}
    </DocLayout>
  )
}
